name: ci

on:
  push:
    paths:
      - "**.py"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install flake8 mypy pytest

    - run: flake8
    - run: mypy

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build
